name: 'build test'
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test-tauri:
    strategy:
      fail-fast: false
      matrix:
        # in future macos-latest
        platform: [ ubuntu-22.04, windows-latest ]

    runs-on: ${{ matrix.platform }}
    environment: build
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable

      - name: install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-22.04'
        run: |
          sudo apt-get update
          sudo apt-get upgrade -y
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libappindicator3-dev librsvg2-dev patchelf libglib2.0-dev libjavascriptcoregtk-4.1-dev libssl-dev

      - name: install frontend dependencies
        run: yarn install

      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAURI_KEY_PASSWORD: ${{ secrets.TAURI_KEY_PASSWORD }}
          TAURI_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
          PKG_CONFIG_PATH: /usr/lib/pkgconfig
