name: Rust integration test

on:
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: install dependencies (ubuntu only)
        run: |
          sudo apt-get update
          sudo apt-get upgrade -y
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libappindicator3-dev librsvg2-dev patchelf libssl-dev

      - name: Install dependencies
        working-directory: ./src-tauri
        run: cargo build --verbose

      - name: Run tests
        working-directory: ./src-tauri
        run: cargo test
